In [3]:
import pandas as pd
import numpy as np 
from sklearn.naive_bayes import GaussianNB

In [4]:
df = pd.read_csv("../all_data_Char.csv")

In [5]:
# create the test and the train data set. 
disordered = df.loc[df["label"]==1.0]
ordered = df.loc[df["label"]==0.0]
# select indices based on a random distributions 
disordered["is_train"] = np.random.uniform(0, 1, len(disordered)) <= 0.885 # calculated based on test/total
ordered["is_train"] = np.random.uniform(0,1, len(ordered)) <= 0.9947 # calculated based on test/total

C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\2563841422.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disordered["is_train"] = np.random.uniform(0, 1, len(disordered)) <= 0.885 # calculated based on test/total
C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\2563841422.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ordered["is_train"] = np.random.uniform(0,1, len(ordered)) <= 0.9947 # calculated based on test/total


In [6]:
df2 = pd.concat([disordered,ordered])
df2 = df2.drop(columns=["sequence"])
train, test = df2[df2['is_train']==True], df2[df2['is_train']==False]

In [7]:
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 248827
Number of observations in the test data: 2591


In [8]:
features = df2.columns[1:5]
y = train.label.to_list()

Gaussian Naive Bayes: not very accurate

In [24]:
gnb = GaussianNB()
from sklearn.preprocessing import MinMaxScaler #fixed import

scaler = MinMaxScaler()
train[features] = scaler.fit_transform(train[features])
test[features] = scaler.transform(test[features])
gnb.fit(train[features], y)
gnb.predict(test[features])
gnb.predict_proba(test[features])[0:10]
# clf = RandomForestClassifier(n_jobs=2, n_estimators =5, random_state=0)
# clf.fit(train[features], y)
# y_pred = gnb.fit(X_train, y_train).predict(X_test)
# clf.predict(test[features])
# clf.predict_proba(test[features])[0:10]

C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\2290067929.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[features] = scaler.fit_transform(train[features])
C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\2290067929.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test[features] = scaler.transform(test[features])


array([[0.89521921, 0.10478079],
       [0.97735134, 0.02264866],
       [0.98177444, 0.01822556],
       [0.98111992, 0.01888008],
       [0.97411162, 0.02588838],
       [0.96188709, 0.03811291],
       [0.95835515, 0.04164485],
       [0.96971378, 0.03028622],
       [0.96861702, 0.03138298],
       [0.97791208, 0.02208792]])

In [25]:
preds = gnb.predict(test[features])

In [26]:
pd.crosstab(test['label'], preds, rownames=['Actual label'], colnames=['Predicted label'])

Predicted label   0.0  1.0
Actual label              
0.0              1274   21
1.0              1245   51

Bernoulli NB

In [21]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
from sklearn.preprocessing import MinMaxScaler #fixed import

scaler = MinMaxScaler()
train[features] = scaler.fit_transform(train[features])
test[features] = scaler.transform(test[features])
bnb.fit(train[features], y)
bnb.predict(test[features])
bnb.predict_proba(test[features])[0:10]

C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\609111722.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[features] = scaler.fit_transform(train[features])
C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\609111722.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test[features] = scaler.transform(test[features])


array([[0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563],
       [0.96035437, 0.03964563]])

In [22]:
predsbnb = bnb.predict(test[features])

In [23]:
pd.crosstab(test['label'], predsbnb, rownames=['Actual label'], colnames=['Predicted label'])

Predicted label   0.0
Actual label         
0.0              1295
1.0              1296

Complement NB

In [18]:
from sklearn.naive_bayes import ComplementNB
from sklearn.preprocessing import MinMaxScaler #fixed import

scaler = MinMaxScaler()
train[features] = scaler.fit_transform(train[features])
test[features] = scaler.transform(test[features])
cnb = ComplementNB()
cnb.fit(train[features], y)
cnb.predict(test[features])
cnb.predict_proba(test[features])[0:10]

C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\1731648552.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[features] = scaler.fit_transform(train[features])
C:\Users\kathe\AppData\Local\Temp\ipykernel_41948\1731648552.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test[features] = scaler.transform(test[features])


array([[0.49944735, 0.50055265],
       [0.49978023, 0.50021977],
       [0.50039136, 0.49960864],
       [0.50035605, 0.49964395],
       [0.49958713, 0.50041287],
       [0.49922318, 0.50077682],
       [0.49996554, 0.50003446],
       [0.49935618, 0.50064382],
       [0.49951568, 0.50048432],
       [0.49979971, 0.50020029]])

In [19]:
predscnb = cnb.predict(test[features])

In [20]:
pd.crosstab(test['label'], predscnb, rownames=['Actual label'], colnames=['Predicted label'])

Predicted label  0.0  1.0
Actual label             
0.0              758  537
1.0              651  645